### ISSUE TITLE
cipher suite support

### ISSUE THREAD

**Issue by dazzafg** [awsdocs/amazon-corretto-11-user-guide#12]
A list of supported Cipher Suites e.g. TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 in version would be great.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
