### ISSUE TITLE
Requirements for Windows 64-bit OS

### ISSUE THREAD

**Issue by Bidwell449** [awsdocs/amazon-corretto-11-user-guide#13]
The documentation does not include information on requirements for installing both the x64 and x86 versions on a 64 bit Windows OS.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
